# Introduction

Democratic backsliding is a broad concept that, at its core, refers to the state-led erosion of democratic institutions. As political scientist Nancy Bermeo observes in her 2016 paper ["On Democratic Backsliding"](https://web.archive.org/web/20210329004055/https://sites.unimi.it/carbone/wp-content/uploads/2018/04/Democratic-backsliding-Bermeo-JOD-2016.pdf) "we now face forms of democratic backsliding that are legitimated through the very institutions that democracy promoters have prioritized." Over the last decade, the phenomenon has gained prominence in the public debate, linked to populism, the far right, and authoritarianism 
(for example:  [“Liberal democracy vs. far‑right authoritarianism in Europe” — *NYTimes*](https://www.nytimes.com/2025/01/11/opinion/editorials/liberal-democracy-far-right-authoritarianism-populism-europe.html?unlocked_article_code=1.xU8.sk1m.XRO8yCuL9f5U&smid=url-share), [“What’s wrong with democracy in Europe?” — *The Economist*](https://www.economist.com/graphic-detail/2025/04/24/whats-wrong-with-democracy-in-europe?giftId=ZDUxMDc3MjItZWFkYS00ZjY3LTljZjktOWRiMDBlMzFjYjlk&utm_campaign=gifted_article)).
 
What drives this erosion? Bermeo identifies two key mechanisms: (i) executive aggrandizement, i.e. the expansion of executive power beyond checks and balances and (ii) strategic electoral manipulation, e.g. restricting voter registration or changing electoral rules to favor incumbents. To these we might add (iii) civil society erosion, e.g. media censorship and restrictions on academic freedom. Several underlying causes have been proposed: (i) economic inequality and discontent; (ii) perceived socio-cultural threats, such as immigration or expanded rights for LGBTQ people and women; and (iii) culture wars and disinformation in an increasingly post-truth media environment.
 
This raises two questions: Is democracy truly in retreat? And is this driven by a single cause or by multiple interacting factors? I believe these questions are crucial for understanding the political landscape we live in and the choices we face as individuals and societies. This analysis explores possible answers by drawing primarily on the V-Dem dataset, with a particular focus on Europe (EU 27 + UK & Switzerland) in the last 20 years (2004 - 2024).
 